### PR TITLE
Port to Coq 8.7

### PR DESCRIPTION
**Pull request by ejgallego**
Ported to Coq 8.7, it compiles, one test fails.

In particular there is a strange problem with `Evarsolve.solve_pattern_eqn` that I couldn't solve, due to a change in API, see https://github.com/coq/coq/commit/aaf75678a13d9c26341e762ab8e56b957cf4c771

The following functions didn't have a proper `EConstr` equivalent so we had to introduce non-efficient workarounds. Please see the items marked `XXX`.

```ocaml
Environ.constant_value_in
Environ.push_rec_types
Evd.evar_filtered_context
Evd.existential_value
Evd.existential_type
Evd.downcast
Evd.define
Evd.set_eq_instances
Reduction.dest_arity
Evarsolve.solve_pattern_eqn
```

### CODE REVIEW

**Comment by ejgallego** [comment]
Reopening as @beta-ziliani has expressed interest and maybe this can be useful.

All the Econstr changes are not done, and they do indeed require some work as unification is kind of worst-case consumer for such an API. Maybe a good first approach is to insert the unsafe casts in the proper places so the plugin compiles, and then refine more.

**Comment by ejgallego** [comment]
Ok, so I did another pass, but I am afraid that this is the limit of what I can contribute; on the other hand the plugin seems not too far from working, but requires knowledge to be sure that the switch to `EConstr` is correct. I guess that everything should be switched to `EConstr` and all the `nf_evar` removed, as it makes no sense otherwise.

**Comment by ejgallego** [comment]
In particular, the API that I didn't know how to port where:

```ocaml
Environ.constant_value_in
Environ.push_rec_types
Evd.evar_filtered_context
Evd.existential_value
Evd.existential_type
Evd.downcast
Evd.define
Evd.set_eq_instances
Reduction.dest_arity
Evarsolve.solve_pattern_eqn
```

maybe @ppedrot has an idea?

**Comment by ejgallego** [comment]
Ok, so now the plugins complies, but a test-case fails @beta-ziliani you need to have a look in particular at 
```
        let t = Evarsolve.solve_pattern_eqn env sigma [] (applist t) in
```
I couldn't figure out what was going on there.

**Comment by beta-ziliani** [comment]
Wow, thanks a lot @ejgallego !!!!

**Comment by ejgallego** [comment]
No problem, let's gets this into Travis! :D

**Comment by beta-ziliani** [comment]
Merged in v1.1-coq8.7. Thanks @ejgallego !

**Pull request closed without merging**
