### PR TITLE
Switch back to .mllib to produce .cmxa file.

### PR DESCRIPTION
**Pull request by Janno**

### CODE REVIEW

**Comment by ejgallego** [comment]
I think this change is not a good idea. Be aware of the motivations to introduce mlpack and double-link problems.

**Comment by beta-ziliani** [comment]
I have no idea of what you're talking about :)
The problem was that Janno couldn't make it work with the mlpack. We need to find out why (it is working for me).

In any case, this is unrelated to the problem I posted just now con Coq's gitter, right?

**Comment by ejgallego** [comment]
> In any case, this is unrelated to the problem I posted just now con Coq's gitter, right?

Right.

> The problem was that Janno couldn't make it work with the mlpack.

I was guessing he was having linking problems due to packing, but then he was doubly-linking in the first place maybe?

**Comment by beta-ziliani** [comment]
I just encountered the same problem: with mlpack now Mtac2 can't find camlMunify.

**Comment by ejgallego** [comment]
Maybe you need to do `open Unicoq` [or `Unicoq_plugin`, I forgot] mllpack puts plugin modules under packing.

**Comment by ejgallego** [comment]
Are you using the MTAC port I submitted?

**Comment by beta-ziliani** [comment]
a modified version by Janno, but essentially yes

**Comment by ejgallego** [comment]
I'll have a look.

**Pull request merged**
