### PR TITLE
Adapt w.r.t. coq/coq#17170.

### PR DESCRIPTION
**Pull request by ppedrot**
Backwards compatible.

### CODE REVIEW

**Comment by ppedrot** [comment]
Ping @Janno just in case.

**Comment by Janno** [comment]
I do not understand the change. (Or the code around it, really.) Is there an easy explanation why the new version is correct?

**Comment by ppedrot** [comment]
If the evar were defined, the call to kind above would have expanded it. Ergo, this branch is only taken when the evar is undefined.

**Comment by Janno** [comment]
Okay, that sounds plausible.

**Pull request merged**
