### PR TITLE
Port to Coq 8.8

### PR DESCRIPTION
**Pull request by ejgallego**
This is necessary in order to add UniCoq to Travis. Tests fail similarly to #6, it also depends on https://github.com/coq/coq/pull/6054

### CODE REVIEW

**Comment by ejgallego** [comment]
So are you, in principle, folks interested in having UniCoq tested by Coq's CI?

**Comment by ejgallego** [comment]
The Coq Plugin Developer Program should replace this kind of PRs, so closing this.

**Comment by beta-ziliani** [comment]
@ejgallego I'd like to move this to Coq's CI, what should I do? I will now respond in time, I promise! I just moved master to Coq's master (which is also compatible with 8.8)

**Comment by ejgallego** [comment]
Cool, just open a PR in the coq repo following the README.ci

**Comment by beta-ziliani** [comment]
mm... I will need a bit more of help than that. what is the process? (feel free to point me to a doc)
The code will still be in our github? Run in travis.org? Is there a default .yml to test against master? And when a change in master breaks something Coq devs will add a PR in unicoq's github? Or...?

**Comment by ejgallego** [comment]
The document is https://github.com/coq/coq/blob/master/dev/ci/README.md sorry. It should answer all these questions otherwise a documentation bug should be filled.

**Comment by beta-ziliani** [comment]
Mmmm... I see MetaCoq is there, and it includes Unicoq.  I suppose it is failing now, right?  I will soon fix Mtac2 and add a PR replacing MetaCoq with Mtac2.

**Pull request closed without merging**
