### PR TITLE
Take primitive integers into account

### PR DESCRIPTION
**Pull request by vbgl**
NB: maybe I chose the wrong branch…

I also make warning 8 fatal, so as to catch earlier such issues.

### CODE REVIEW

**Comment by ejgallego** [comment]
We choose the same branch [see #24] hehe maybe both of us are wrong :)

I think we can just take #24 as it includes this fix and a couple more.

Regarding the flags I'd rather try to push this upstream, see https://github.com/coq/coq/pull/9605

**Comment by beta-ziliani** [comment]
IIUC this is solved already, so we could delete this PR, right? @ejgallego @vbgl

**Comment by ejgallego** [comment]
I am not sure if the current solution is really a fix or just a patch that has left unicoq broken on the primitive integers but silenced the warnings.

**Comment by beta-ziliani** [comment]
oh, it doesn't solve it, that's for sure, but will fix it when the need arise :-)

**Pull request closed without merging**
